# Adapter-Hub task definition
# Defines a broader task/ category that is divided into specific subtasks.
# --------------------

# The short identifier of this task.
# Example: sentiment
task: ged

# The full name of the task that should be displayed e.g. on the website.
# Example: Sentiment Analysis
displayname: "Grammatical Error Detection"

# A short description of this task (max. 500 chars).
description: |
  The task of grammatical error detection (GED) deals with identifying tokens in a sentence which require editing to construct a grammatically correct sentence.
