# Adapter-Hub task definition
# Defines a broader task/ category that is divided into specific subtasks.
# --------------------

# The short identifier of this task.
# Example: sentiment
task: "lm"

# The full name of the task that should be displayed e.g. on the website.
# Example: Sentiment Analysis
displayname: "Lamguage Modelling"

# A short description of this task (max. 500 chars).
description: "The model learns which words appear in which contexts and is able to produce texts."
