# Adapter-Hub task definition
# Defines a broader task/ category that is divided into specific subtasks.
# --------------------

# The short identifier of this task.
# Example: sentiment
task: wikiann_ner

# The full name of the task that should be displayed e.g. on the website.
# Example: Sentiment Analysis
displayname: |
    Wiki Ann NER

# A short description of this task (max. 500 chars).
description: |
    Named Entity Recognition identifies named entities in a text. It classifies the found named entities as people, locations, organisations, ...
